### PR TITLE
fixed SeqCst error (#15) and updated to 0.2.4

### PR DESCRIPTION
**Pull request by bharadwaj6**
rustbox now builds with latest rust nightly.

### CODE REVIEW

**Comment by gchp** [comment]
Great, thank you!

**Comment by gchp** [comment]
Just published `0.2.4` to the cargo registry.

**Comment by bharadwaj6** [comment]
@gchp : Thanks... I was doing this to fix the iota build, but I see that you did it already... :+1

**Comment by gchp** [comment]
Beat you to it :smile: Let me know if you find other issues!

**Pull request merged**
