### PR TITLE
Stable support

### PR DESCRIPTION
**Pull request by Yamakaky**
With these changes, it compiles on stable 1.1. The Send is a problem though.

See  #36

### CODE REVIEW

**Comment by jayrandez** [comment]
Can you determine whether or not RustBox is "Send" when the negative trait is removed?

 You can force it to be not "Send" by adding a PhantomData marker for a type which is "Not Send"

**Comment by Yamakaky** [comment]
What's cool with rust (and haskell (and cool languages)) is that you always have something to learn ^^

**Comment by Yamakaky** [comment]
Did you have time to review the changes ?

**Comment by gchp** [comment]
Sorry for the delay, thanks for this @Yamakaky!

**Pull request merged**
