### PR TITLE
Add suspend support

### PR DESCRIPTION
**Pull request by jmacdonald**
This PR is based on the changes in #81.

In a threaded application, temporarily tearing down a Rustbox instance (to suspend the application) can be problematic. This adds a `suspend` method that locks access to a Rustbox instance across all threads, shuts down Termbox, and defers to the caller before re-initializing Termbox and releasing all locks.

### CODE REVIEW

**Comment by gchp** [comment]
Looks good - thanks!

**Comment by jmacdonald** [comment]
Any chance we can roll a new `0.11.0` release? This last PR covers all of the changes I was blocked on. :smile:

**Comment by gchp** [comment]
@jmacdonald published!

**Comment by jmacdonald** [comment]
Thanks, @gchp! 🍻

**Pull request merged**
