### PR TITLE
mark `RustBox` `Send`, but still not `Sync`

### PR DESCRIPTION
**Pull request by dsprenkels**
I propose another solution for #41 along #44.

The RustBox type is not thread safe, in the sense that multiple
threads may never alter the mutable state of a shared RustBox
at the same time, so it should not be marked Sync.
However, a RustBox type _can_ safely be sent between threads so
it _should_ be marked Send.

This patch makes it possible to wrap a RustBox struct inside
a Mutex type, so that it can still be used when the programmer
decides to do the synchronization theirself.

### CODE REVIEW

**Comment by panicbit** [comment]
I think there are still some problems:

```
note: `core::cell::UnsafeCell<()>` cannot be shared between threads safely
note: required because it appears within the type `core::marker::PhantomData<core::cell::UnsafeCell<()>>`
note: required because it appears within the type `rustbox::RustBox`
```

**Comment by panicbit** [comment]
Ah, NVM, it was complaining about Sync, not about Send.

**Comment by dsprenkels** [comment]
For sending the RustBox type between threads, you can now wrap it inside a `std::sync::Mutex`. :)

**Comment by steakknife** [comment]
Works great! 👍

**Comment by ritiek** [comment]
I think it would be helpful to have an example that implements threading in the examples directory.

**Comment by gchp** [comment]
I'm really sorry for the significant delay on this. I appreciate you you all giving your feedback and for @dsprenkels for submitting the patch. Looks good to me.

**Comment by dsprenkels** [comment]
No problem! :smile:

**Comment by jmacdonald** [comment]
@gchp this is great! Any chance you can cut a new version of this crate with these changes? 😄🙏

**Comment by gchp** [comment]
@jmacdonald I just published 0.10.0

**Comment by jmacdonald** [comment]
Thanks, @gchp!

**Comment by gchp** [comment]
No problem. Apologies for the delay. Let me know if you notice any issues.

**Pull request merged**
